### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by marciomansur** [MiguhRuiz/block-storage#1]
Good morning,

First of all, very nice module!

I still didn't have time to play with it, but it's a nice encapsulation.

It'd be nice to control the usage flow with promises, that is still very used today.

It's a suggestion, maybe I can help.

**Comment by MiguhRuiz** [comment]
Good afternoon! 😄 

I'm very greatful because of your feedback. I want to know if what you mean is that I have to improve the documentation writing that the module can work with promises and a few examples of it.

Waiting for your answer. 👍

**Comment by marciomansur** [comment]
Hi!

Yes, this was my suggestion. Also, it was a question, if you have implemented promises to control the flow of your functions. If you want an example, I can write one with the 'promisefyAll' using the bluebird method.

Thank you!

**Comment by MiguhRuiz** [comment]
Hi!

The module supports both promises and callbacks. As you can see, for example the `get()` function uses bluebird in order to make it supportable:

``` javascript
const request = require('request-promise')
const Promise = require('bluebird')

class Client {

  constructor (opt) {
    this.options = opt || {}
    this.token = this.options.token
    this.url = 'https://api.digitalocean.com/v2/volumes'
  }

  get(id, callback) {
    const opts = {
      method: 'GET',
      uri: `${this.url}/${id}`,
      headers: {
        'Authorization': `Bearer ${this.token}`
      },
      json: true
    }

    return Promise.resolve(request(opts)).asCallback(callback)
  }

```

About the docs, I'll improve them.

Thank you!

**Comment by MiguhRuiz** [comment]
If you check [this example](https://tonicdev.com/57cb105a0540e114006f2eda/57cb13534bcf3f140022107b) I've just made using a real Digital Ocean API token you'll see that promises work with the module.

**Comment by MiguhRuiz** [comment]
58bd8cb7acb6b10e51aa6cdd58d148e2189eb6c9

**Comment by MiguhRuiz** [comment]
Please, take a look at the updated version of the docs and tell me if you think that I should improve them more and how.

Have a nice day! 😄

**Comment by MiguhRuiz** [comment]
I close this issue because I haven't recieve any notice. If you want to discuss more about it feel free to re-open it.
